<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes. All rights reserved.
 * See COPYING.txt for license details.
 */

/*
 * This is a simple query argument dump template used to test passing record IDs from actions and mass actions.
 */

/** @var \Magento\Framework\View\Element\Template $block */
/** @var \Magento\Framework\Escaper $escaper */

?>
<pre><?= $escaper->escapeHtml(json_encode($block->getRequest()->getParams() ?? [], JSON_PRETTY_PRINT)); ?></pre>
